/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pvyzbpcjbjcxqwxlryxh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2eXpicGNqYmpjeHF3eGxyeXhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NTA5OTMsImV4cCI6MjA3NDEyNjk5M30.i-fJc7puQG-azClNax26_WQFgcO3uEZWeGtzbWrJnwE"